"""
Initial migration.

This Alembic revision creates the users, transactions, ledger_entries
and webhook_events tables defined in the models.  Additional columns or
tables can be added in subsequent revisions.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.Integer(), nullable=False),
        sa.Column('fiat_currency', sa.String(length=3), nullable=True),
        sa.Column('lang', sa.String(length=2), nullable=True),
        sa.Column('tone', sa.String(length=20), nullable=True),
        sa.Column('ton_wallet', sa.String(length=100), nullable=True),
        sa.Column('evm_wallet', sa.String(length=100), nullable=True),
        sa.Column('sol_wallet', sa.String(length=100), nullable=True),
        sa.Column('kyc_status', sa.Enum('pending', 'approved', 'rejected', name='kycstatus'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('telegram_id')
    )
    op.create_table(
        'transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('tx_hash', sa.String(length=100), nullable=True),
        sa.Column('order_id', sa.String(length=100), nullable=True),
        sa.Column('crypto_amount', sa.Float(), nullable=False),
        sa.Column('fiat_amount', sa.Float(), nullable=False),
        sa.Column('token', sa.String(length=10), nullable=False),
        sa.Column('chain', sa.String(length=20), nullable=False),
        sa.Column('status', sa.Enum('initiated', 'quoted', 'payment_pending', 'signed', 'funded', 'executed', 'completed', 'failed', name='orderstatus'), nullable=False),
        sa.Column('tx_type', sa.String(length=10), nullable=True),
        sa.Column('fee_usd', sa.Float(), nullable=True),
        sa.Column('payout_status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_id'),
        sa.UniqueConstraint('tx_hash')
    )
    op.create_table(
        'ledger_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=True),
        sa.Column('entry_type', sa.Enum('debit', 'credit', name='ledgerentrytype'), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'webhook_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=100), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=True),
        sa.Column('payload', sa.String(), nullable=True),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_events')
    op.drop_table('ledger_entries')
    op.drop_table('transactions')
    op.drop_table('users')
    # ### end Alembic commands ###
